name: Update CHANGELOG.md

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  git-chglog:
    name: Setup Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@main
      - uses: actions/setup-node@v3
        with:
          go-version: 'stable'
          node-version: '18.x'
      - name: Update CHANGELOG.md with git-chglog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          git fetch --prune --unshallow --tags
          git-chglog -o CHANGELOG.md
      - name: Just a sec
        run: |
          yarn build:chglog 
          yarn prettier
      - name: Almost done
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com 
          git config user.name github-actions[bot]
          git add ./CHANGELOG.md
          git commit -m "change: Update CHANGELOG.md" -m "Updating CHANGELOG.md using workflows"  -m "Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>" || echo "Tree is clean"
          git push origin master || echo "Tree is clean"
