name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  node-build:
    name: Publishing package for NodeJs and Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn config set enableImmutableInstalls false
      - run: yarn install
      - run: yarn build
      - run: npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  browser-build:
    name: Publishing package for Browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn config set enableImmutableInstalls false
      - run: yarn install
      - run: yarn add aes-js browserify-zlib buffer crypto-browserify events os-browserify path-browserify util stream-browserify process
      - run: node ./generator/build_browser/index.js
      - run: yarn build
      - run: npm publish --tag browser --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
