name: Sync the error reference
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  sync-tl:
    name: Setup NodeJS and Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Sync error references
        run: |
          deno run --allow-all ./generator/sync-error/index.mjs
          yarn config set enableImmutableInstalls false
          yarn install
          yarn build:error
          yarn build
          yarn prettier
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git pull origin master
          git add ./generator/* ./src/errors/*
          git commit -m "change: Update Error Reference" -m "Updating Error Reference using workflows"  -m "Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>" || echo "Tree is clean"
          git push origin master || echo "Tree is clean"
